<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\GameRace;
use Illuminate\Database\Seeder;

class GameRaceSeeder extends Seeder
{
    /**
     * Seed the URA scenario race catalog.
     *
     * Distance categories:
     *   sprint      ≤ 1400m
     *   mile        1401–1800m
     *   medium      1801–2400m
     *   long        2401–3000m
     *   super_long  > 3000m
     */
    public function run(): void
    {
        $races = $this->getRaces();

        foreach ($races as $race) {
            GameRace::query()->updateOrCreate(
                ['slug' => $race['slug']],
                $race,
            );
        }
    }

    /**
     * @return array<int, array<string, mixed>>
     */
    private function getRaces(): array
    {
        return [
            // ──────────────────────────────────────────────────
            // JUNIOR PHASE  (Year 1 — April through December)
            // ──────────────────────────────────────────────────

            [
                'slug' => 'debut-race',
                'name_en' => 'Debut Race',
                'name_jp' => 'デビュー戦',
                'grade' => 'Debut',
                'phase' => 'junior',
                'surface' => 'turf',
                'distance_meters' => 1600,
                'distance_category' => 'mile',
                'venue' => 'Various',
                'season' => 'spring',
                'month_label' => 'April–May Year 1',
                'year_in_scenario' => 1,
                'fan_requirement' => 0,
                'fans_reward' => 100,
                'sp_reward' => 0,
                'notes' => 'First race of the career. Any eligible OP track.',
            ],
            [
                'slug' => 'niiza-kinenkai',
                'name_en' => 'Niiza Commemorative',
                'name_jp' => '新座記念',
                'grade' => 'Pre-OP',
                'phase' => 'junior',
                'surface' => 'turf',
                'distance_meters' => 1600,
                'distance_category' => 'mile',
                'venue' => 'Tokyo',
                'season' => 'spring',
                'month_label' => 'May Year 1',
                'year_in_scenario' => 1,
                'fan_requirement' => 0,
                'fans_reward' => 150,
                'sp_reward' => 5,
            ],
            [
                'slug' => 'baba-kinenkai',
                'name_en' => 'Baba Commemorative',
                'name_jp' => '馬場記念',
                'grade' => 'Pre-OP',
                'phase' => 'junior',
                'surface' => 'turf',
                'distance_meters' => 1600,
                'distance_category' => 'mile',
                'venue' => 'Nakayama',
                'season' => 'spring',
                'month_label' => 'May Year 1',
                'year_in_scenario' => 1,
                'fan_requirement' => 0,
                'fans_reward' => 150,
                'sp_reward' => 5,
            ],
            [
                'slug' => 'tv-tokyo-hai',
                'name_en' => 'TV Tokyo Cup',
                'name_jp' => 'テレビ東京杯',
                'grade' => 'OP',
                'phase' => 'junior',
                'surface' => 'turf',
                'distance_meters' => 1600,
                'distance_category' => 'mile',
                'venue' => 'Tokyo',
                'season' => 'summer',
                'month_label' => 'July Year 1',
                'year_in_scenario' => 1,
                'fan_requirement' => 0,
                'fans_reward' => 200,
                'sp_reward' => 5,
            ],
            [
                'slug' => 'hakodate-nisei',
                'name_en' => 'Hakodate 2-Year-Old Stakes',
                'name_jp' => '函館2歳ステークス',
                'grade' => 'OP',
                'phase' => 'junior',
                'surface' => 'turf',
                'distance_meters' => 1200,
                'distance_category' => 'sprint',
                'venue' => 'Hakodate',
                'season' => 'summer',
                'month_label' => 'July Year 1',
                'year_in_scenario' => 1,
                'fan_requirement' => 0,
                'fans_reward' => 200,
                'sp_reward' => 5,
            ],
            [
                'slug' => 'sapporo-nikkei',
                'name_en' => 'Sapporo Nikkei Open',
                'name_jp' => '札幌日経OP',
                'grade' => 'OP',
                'phase' => 'junior',
                'surface' => 'turf',
                'distance_meters' => 1200,
                'distance_category' => 'sprint',
                'venue' => 'Sapporo',
                'season' => 'summer',
                'month_label' => 'August Year 1',
                'year_in_scenario' => 1,
                'fan_requirement' => 0,
                'fans_reward' => 180,
                'sp_reward' => 5,
            ],
            [
                'slug' => 'kokura-nisai-stakes',
                'name_en' => 'Kokura 2-Year-Old Stakes',
                'name_jp' => '小倉2歳ステークス',
                'grade' => 'G3',
                'phase' => 'junior',
                'surface' => 'turf',
                'distance_meters' => 1200,
                'distance_category' => 'sprint',
                'venue' => 'Kokura',
                'season' => 'summer',
                'month_label' => 'August Year 1',
                'year_in_scenario' => 1,
                'fan_requirement' => 0,
                'fans_reward' => 280,
                'sp_reward' => 10,
                'notes' => 'Earliest graded race of the season. Sprint specialists shine here.',
            ],
            [
                'slug' => 'sapporo-nisai-stakes',
                'name_en' => 'Sapporo 2-Year-Old Stakes',
                'name_jp' => '札幌2歳ステークス',
                'grade' => 'G3',
                'phase' => 'junior',
                'surface' => 'turf',
                'distance_meters' => 1800,
                'distance_category' => 'mile',
                'venue' => 'Sapporo',
                'season' => 'summer',
                'month_label' => 'September Year 1',
                'year_in_scenario' => 1,
                'fan_requirement' => 0,
                'fans_reward' => 300,
                'sp_reward' => 10,
                'notes' => 'Classic distance G3 preview. Good for identifying future Kikuka Sho candidates.',
            ],
            [
                'slug' => 'niigata-nisai-stakes',
                'name_en' => 'Niigata 2-Year-Old Stakes',
                'name_jp' => '新潟2歳ステークス',
                'grade' => 'G3',
                'phase' => 'junior',
                'surface' => 'turf',
                'distance_meters' => 1600,
                'distance_category' => 'mile',
                'venue' => 'Niigata',
                'season' => 'summer',
                'month_label' => 'September Year 1',
                'year_in_scenario' => 1,
                'fan_requirement' => 0,
                'fans_reward' => 290,
                'sp_reward' => 10,
                'notes' => 'Niigata straight course. Speed-heavy character advantage.',
            ],
            [
                'slug' => 'keisei-hai-junior',
                'name_en' => 'Keisei Cup (Junior)',
                'name_jp' => '京成杯',
                'grade' => 'G3',
                'phase' => 'junior',
                'surface' => 'turf',
                'distance_meters' => 2000,
                'distance_category' => 'medium',
                'venue' => 'Nakayama',
                'season' => 'winter',
                'month_label' => 'January Year 1',
                'year_in_scenario' => 1,
                'fan_requirement' => 0,
                'fans_reward' => 350,
                'sp_reward' => 15,
            ],
            [
                'slug' => 'tokyo-sports-hai-nisai',
                'name_en' => 'Tokyo Sports Hai 2-Year-Old Stakes',
                'name_jp' => '東京スポーツ杯2歳ステークス',
                'grade' => 'OP',
                'phase' => 'junior',
                'surface' => 'turf',
                'distance_meters' => 1800,
                'distance_category' => 'mile',
                'venue' => 'Tokyo',
                'season' => 'autumn',
                'month_label' => 'November Year 1',
                'year_in_scenario' => 1,
                'fan_requirement' => 0,
                'fans_reward' => 350,
                'sp_reward' => 15,
                'notes' => 'Prestigious junior OP at Tokyo. Good bridge between summer G3s and the year-end G1s.',
            ],
            [
                'slug' => 'mainichi-hai',
                'name_en' => 'Mainichi Cup',
                'name_jp' => '毎日杯',
                'grade' => 'G3',
                'phase' => 'junior',
                'surface' => 'turf',
                'distance_meters' => 1800,
                'distance_category' => 'mile',
                'venue' => 'Hanshin',
                'season' => 'spring',
                'month_label' => 'March Year 2 / June Year 1',
                'year_in_scenario' => 1,
                'fan_requirement' => 0,
                'fans_reward' => 300,
                'sp_reward' => 10,
                'notes' => 'Important junior G3. Good SP reward.',
            ],
            [
                'slug' => 'tulip-sho',
                'name_en' => 'Tulip Stakes',
                'name_jp' => 'チューリップ賞',
                'grade' => 'G3',
                'phase' => 'classic',
                'surface' => 'turf',
                'distance_meters' => 1600,
                'distance_category' => 'mile',
                'venue' => 'Hanshin',
                'season' => 'spring',
                'month_label' => 'March Year 2',
                'year_in_scenario' => 1,
                'fan_requirement' => 0,
                'fans_reward' => 300,
                'sp_reward' => 10,
                'notes' => 'Fillies only in real life; open race in URA scenario.',
            ],
            [
                'slug' => 'asahi-hai-futurity',
                'name_en' => 'Asahi Hai Futurity Stakes',
                'name_jp' => '朝日杯フューチュリティステークス',
                'grade' => 'G1',
                'phase' => 'junior',
                'surface' => 'turf',
                'distance_meters' => 1600,
                'distance_category' => 'mile',
                'venue' => 'Hanshin',
                'season' => 'winter',
                'month_label' => 'December Year 1',
                'year_in_scenario' => 1,
                'fan_requirement' => 100,
                'fans_reward' => 1000,
                'sp_reward' => 35,
                'notes' => 'Junior G1 mile race. Win to build fan base before Classic.',
            ],
            [
                'slug' => 'hopeful-stakes',
                'name_en' => 'Hopeful Stakes',
                'name_jp' => 'ホープフルステークス',
                'grade' => 'G1',
                'phase' => 'junior',
                'surface' => 'turf',
                'distance_meters' => 2000,
                'distance_category' => 'medium',
                'venue' => 'Nakayama',
                'season' => 'winter',
                'month_label' => 'December Year 1',
                'year_in_scenario' => 1,
                'fan_requirement' => 100,
                'fans_reward' => 1000,
                'sp_reward' => 35,
                'notes' => 'Junior G1 medium distance. Target for middle/long-distance builds.',
            ],

            // ──────────────────────────────────────────────────
            // CLASSIC PHASE  (Year 2 — January through December)
            // ──────────────────────────────────────────────────

            [
                'slug' => 'fairy-stakes',
                'name_en' => 'Fairy Stakes',
                'name_jp' => 'フェアリーステークス',
                'grade' => 'G3',
                'phase' => 'classic',
                'surface' => 'turf',
                'distance_meters' => 1600,
                'distance_category' => 'mile',
                'venue' => 'Nakayama',
                'season' => 'winter',
                'month_label' => 'January Year 2',
                'year_in_scenario' => 2,
                'fan_requirement' => 300,
                'fans_reward' => 400,
                'sp_reward' => 15,
                'notes' => 'Classic G3 mile for fillies. Early-year target for mile specialists.',
            ],
            [
                'slug' => 'hyacinth-stakes',
                'name_en' => 'Hyacinth Stakes',
                'name_jp' => 'ヒヤシンスステークス',
                'grade' => 'OP',
                'phase' => 'classic',
                'surface' => 'dirt',
                'distance_meters' => 1600,
                'distance_category' => 'mile',
                'venue' => 'Tokyo',
                'season' => 'winter',
                'month_label' => 'February Year 2',
                'year_in_scenario' => 2,
                'fan_requirement' => 200,
                'fans_reward' => 300,
                'sp_reward' => 10,
                'notes' => 'OP dirt mile. Gateway for dirt specialists entering Classic year.',
            ],
            [
                'slug' => 'queen-cup',
                'name_en' => 'Queen Cup',
                'name_jp' => 'クイーンカップ',
                'grade' => 'G3',
                'phase' => 'classic',
                'surface' => 'turf',
                'distance_meters' => 1600,
                'distance_category' => 'mile',
                'venue' => 'Tokyo',
                'season' => 'winter',
                'month_label' => 'February Year 2',
                'year_in_scenario' => 2,
                'fan_requirement' => 300,
                'fans_reward' => 450,
                'sp_reward' => 15,
                'notes' => 'Classic G3 mile at Tokyo. Good prep for NHK Mile Cup.',
            ],
            [
                'slug' => 'sumire-stakes',
                'name_en' => 'Sumire Stakes',
                'name_jp' => 'すみれステークス',
                'grade' => 'G3',
                'phase' => 'classic',
                'surface' => 'turf',
                'distance_meters' => 2200,
                'distance_category' => 'medium',
                'venue' => 'Hanshin',
                'season' => 'winter',
                'month_label' => 'February Year 2',
                'year_in_scenario' => 2,
                'fan_requirement' => 300,
                'fans_reward' => 450,
                'sp_reward' => 15,
                'notes' => 'Classic G3 medium distance. Good stamina prep for Triple Crown.',
            ],
            [
                'slug' => 'kyoto-kinen',
                'name_en' => 'Kyoto Kinen',
                'name_jp' => '京都記念',
                'grade' => 'G2',
                'phase' => 'classic',
                'surface' => 'turf',
                'distance_meters' => 2200,
                'distance_category' => 'medium',
                'venue' => 'Kyoto/Hanshin',
                'season' => 'winter',
                'month_label' => 'February Year 2',
                'year_in_scenario' => 2,
                'fan_requirement' => 500,
                'fans_reward' => 600,
                'sp_reward' => 20,
            ],
            [
                'slug' => 'yayoi-sho',
                'name_en' => 'Yayoi Sho (Japanese 2000 Guineas Trial)',
                'name_jp' => '弥生賞',
                'grade' => 'G2',
                'phase' => 'classic',
                'surface' => 'turf',
                'distance_meters' => 2000,
                'distance_category' => 'medium',
                'venue' => 'Nakayama',
                'season' => 'spring',
                'month_label' => 'March Year 2',
                'year_in_scenario' => 2,
                'fan_requirement' => 500,
                'fans_reward' => 600,
                'sp_reward' => 20,
                'notes' => 'Classic G2 trial for Satsuki Sho. Important Nakayama prep race.',
            ],
            [
                'slug' => 'spring-stakes',
                'name_en' => 'Spring Stakes',
                'name_jp' => 'スプリングステークス',
                'grade' => 'G2',
                'phase' => 'classic',
                'surface' => 'turf',
                'distance_meters' => 1800,
                'distance_category' => 'mile',
                'venue' => 'Nakayama',
                'season' => 'spring',
                'month_label' => 'March Year 2',
                'year_in_scenario' => 2,
                'fan_requirement' => 400,
                'fans_reward' => 550,
                'sp_reward' => 20,
                'notes' => 'Classic G2 mile stepping stone. Good bridge between G3s and NHK Mile Cup.',
            ],
            [
                'slug' => 'satsuki-sho',
                'name_en' => 'Satsuki Sho (Japanese 2000 Guineas)',
                'name_jp' => '皐月賞',
                'grade' => 'G1',
                'phase' => 'classic',
                'surface' => 'turf',
                'distance_meters' => 2000,
                'distance_category' => 'medium',
                'venue' => 'Nakayama',
                'season' => 'spring',
                'month_label' => 'April Year 2',
                'year_in_scenario' => 2,
                'fan_requirement' => 1000,
                'fans_reward' => 1800,
                'sp_reward' => 55,
                'notes' => 'First leg of the Japanese Triple Crown. Speed and power focused.',
            ],
            [
                'slug' => 'antares-stakes',
                'name_en' => 'Antares Stakes',
                'name_jp' => 'アンタレスステークス',
                'grade' => 'OP',
                'phase' => 'classic',
                'surface' => 'dirt',
                'distance_meters' => 1800,
                'distance_category' => 'mile',
                'venue' => 'Hanshin',
                'season' => 'spring',
                'month_label' => 'April Year 2',
                'year_in_scenario' => 2,
                'fan_requirement' => 200,
                'fans_reward' => 350,
                'sp_reward' => 10,
                'notes' => 'OP dirt mile in Classic year. Best target for dirt-specialist builds.',
            ],
            [
                'slug' => 'victoria-mile',
                'name_en' => 'Victoria Mile',
                'name_jp' => 'ヴィクトリアマイル',
                'grade' => 'G1',
                'phase' => 'all',
                'surface' => 'turf',
                'distance_meters' => 1600,
                'distance_category' => 'mile',
                'venue' => 'Tokyo',
                'season' => 'spring',
                'month_label' => 'May Year 2 & 3',
                'year_in_scenario' => null,
                'fan_requirement' => 1500,
                'fans_reward' => 1800,
                'sp_reward' => 50,
                'notes' => 'Spring G1 mile at Tokyo. Top mile specialist target available Classic and Senior.',
            ],
            [
                'slug' => 'nhk-mile-cup',
                'name_en' => 'NHK Mile Cup',
                'name_jp' => 'NHKマイルカップ',
                'grade' => 'G1',
                'phase' => 'classic',
                'surface' => 'turf',
                'distance_meters' => 1600,
                'distance_category' => 'mile',
                'venue' => 'Tokyo',
                'season' => 'spring',
                'month_label' => 'May Year 2',
                'year_in_scenario' => 2,
                'fan_requirement' => 1000,
                'fans_reward' => 1600,
                'sp_reward' => 50,
                'notes' => 'Classic G1 for mile specialists. Only available in Classic year.',
            ],
            [
                'slug' => 'japan-derby',
                'name_en' => 'Japan Derby (Tokyo Yushun)',
                'name_jp' => '東京優駿（日本ダービー）',
                'grade' => 'G1',
                'phase' => 'classic',
                'surface' => 'turf',
                'distance_meters' => 2400,
                'distance_category' => 'long',
                'venue' => 'Tokyo',
                'season' => 'spring',
                'month_label' => 'May–June Year 2',
                'year_in_scenario' => 2,
                'fan_requirement' => 1200,
                'fans_reward' => 2100,
                'sp_reward' => 60,
                'notes' => 'Second leg of Triple Crown. Most prestigious Classic race. Long distance.',
            ],
            [
                'slug' => 'takarazuka-kinen',
                'name_en' => 'Takarazuka Kinen',
                'name_jp' => '宝塚記念',
                'grade' => 'G1',
                'phase' => 'all',
                'surface' => 'turf',
                'distance_meters' => 2200,
                'distance_category' => 'medium',
                'venue' => 'Hanshin',
                'season' => 'summer',
                'month_label' => 'June Year 2 & 3',
                'year_in_scenario' => null,
                'fan_requirement' => 2000,
                'fans_reward' => 2000,
                'sp_reward' => 55,
                'notes' => 'Mid-year G1. Good stamina/guts check. Available in both Classic and Senior.',
            ],
            [
                'slug' => 'sapporo-kinen',
                'name_en' => 'Sapporo Kinen',
                'name_jp' => '札幌記念',
                'grade' => 'G2',
                'phase' => 'all',
                'surface' => 'turf',
                'distance_meters' => 2000,
                'distance_category' => 'medium',
                'venue' => 'Sapporo',
                'season' => 'summer',
                'month_label' => 'August Year 2 & 3',
                'year_in_scenario' => null,
                'fan_requirement' => 800,
                'fans_reward' => 750,
                'sp_reward' => 22,
                'notes' => 'Summer G2 at Sapporo. Good bridge target before autumn G1 season.',
            ],
            [
                'slug' => 'rose-stakes',
                'name_en' => 'Rose Stakes',
                'name_jp' => 'ローズステークス',
                'grade' => 'G2',
                'phase' => 'classic',
                'surface' => 'turf',
                'distance_meters' => 2000,
                'distance_category' => 'medium',
                'venue' => 'Nakayama',
                'season' => 'autumn',
                'month_label' => 'September Year 2',
                'year_in_scenario' => 2,
                'fan_requirement' => 600,
                'fans_reward' => 700,
                'sp_reward' => 22,
                'notes' => 'Classic G2 medium. Good autumn prep for Kikuka Sho candidates.',
            ],
            [
                'slug' => 'asahi-challenge-cup',
                'name_en' => 'Asahi Challenge Cup',
                'name_jp' => '朝日チャレンジカップ',
                'grade' => 'G3',
                'phase' => 'all',
                'surface' => 'turf',
                'distance_meters' => 2000,
                'distance_category' => 'medium',
                'venue' => 'Hanshin',
                'season' => 'autumn',
                'month_label' => 'September Year 2 & 3',
                'year_in_scenario' => null,
                'fan_requirement' => 500,
                'fans_reward' => 500,
                'sp_reward' => 15,
                'notes' => 'All-phase G3 medium. Useful filler race in autumn stretch.',
            ],
            [
                'slug' => 'sprinters-stakes',
                'name_en' => 'Sprinters Stakes',
                'name_jp' => 'スプリンターズステークス',
                'grade' => 'G1',
                'phase' => 'all',
                'surface' => 'turf',
                'distance_meters' => 1200,
                'distance_category' => 'sprint',
                'venue' => 'Nakayama',
                'season' => 'autumn',
                'month_label' => 'October Year 2 & 3',
                'year_in_scenario' => null,
                'fan_requirement' => 1500,
                'fans_reward' => 1800,
                'sp_reward' => 45,
                'notes' => 'Top sprint G1. Best for speed/escape-style characters.',
            ],
            [
                'slug' => 'fuji-stakes',
                'name_en' => 'Fuji Stakes',
                'name_jp' => '富士ステークス',
                'grade' => 'G3',
                'phase' => 'all',
                'surface' => 'turf',
                'distance_meters' => 1600,
                'distance_category' => 'mile',
                'venue' => 'Tokyo',
                'season' => 'autumn',
                'month_label' => 'October Year 2 & 3',
                'year_in_scenario' => null,
                'fan_requirement' => 400,
                'fans_reward' => 500,
                'sp_reward' => 15,
                'notes' => 'Tokyo G3 mile. Common prep race for Mile Championship.',
            ],
            [
                'slug' => 'shuka-sho',
                'name_en' => 'Shuka Sho',
                'name_jp' => '秋華賞',
                'grade' => 'G1',
                'phase' => 'classic',
                'surface' => 'turf',
                'distance_meters' => 2000,
                'distance_category' => 'medium',
                'venue' => 'Kyoto/Hanshin',
                'season' => 'autumn',
                'month_label' => 'October Year 2',
                'year_in_scenario' => 2,
                'fan_requirement' => 1000,
                'fans_reward' => 1800,
                'sp_reward' => 50,
                'notes' => 'Classic G1 for fillies. The female counterpart to Kikuka Sho in the autumn.',
            ],
            [
                'slug' => 'kikuka-sho',
                'name_en' => 'Kikuka Sho (Japanese St. Leger)',
                'name_jp' => '菊花賞',
                'grade' => 'G1',
                'phase' => 'classic',
                'surface' => 'turf',
                'distance_meters' => 3000,
                'distance_category' => 'long',
                'venue' => 'Kyoto/Hanshin',
                'season' => 'autumn',
                'month_label' => 'October Year 2',
                'year_in_scenario' => 2,
                'fan_requirement' => 1500,
                'fans_reward' => 2000,
                'sp_reward' => 60,
                'stat_requirements' => ['stamina' => 600, 'guts' => 400],
                'notes' => 'Third leg of Triple Crown. Demands high stamina. Long-distance specialists only.',
            ],
            [
                'slug' => 'tenno-sho-autumn',
                'name_en' => 'Tenno Sho (Autumn)',
                'name_jp' => '天皇賞（秋）',
                'grade' => 'G1',
                'phase' => 'all',
                'surface' => 'turf',
                'distance_meters' => 2000,
                'distance_category' => 'medium',
                'venue' => 'Tokyo',
                'season' => 'autumn',
                'month_label' => 'October Year 2 & 3',
                'year_in_scenario' => null,
                'fan_requirement' => 2000,
                'fans_reward' => 2200,
                'sp_reward' => 65,
                'notes' => 'Top prestige autumn G1 at Tokyo. Well-balanced stat check.',
            ],
            [
                'slug' => 'mile-championship',
                'name_en' => 'Mile Championship',
                'name_jp' => 'マイルチャンピオンシップ',
                'grade' => 'G1',
                'phase' => 'all',
                'surface' => 'turf',
                'distance_meters' => 1600,
                'distance_category' => 'mile',
                'venue' => 'Kyoto/Hanshin',
                'season' => 'autumn',
                'month_label' => 'November Year 2 & 3',
                'year_in_scenario' => null,
                'fan_requirement' => 2000,
                'fans_reward' => 2000,
                'sp_reward' => 55,
                'notes' => 'Premier mile G1. Target for NHK Mile Cup winners.',
            ],
            [
                'slug' => 'mainichi-okan',
                'name_en' => 'Mainichi Okan',
                'name_jp' => '毎日王冒',
                'grade' => 'G2',
                'phase' => 'all',
                'surface' => 'turf',
                'distance_meters' => 1800,
                'distance_category' => 'mile',
                'venue' => 'Tokyo',
                'season' => 'autumn',
                'month_label' => 'October Year 2 & 3',
                'year_in_scenario' => null,
                'fan_requirement' => 800,
                'fans_reward' => 700,
                'sp_reward' => 22,
                'notes' => 'G2 mile at Tokyo. Autumn prep target for Mile Championship challengers.',
            ],
            [
                'slug' => 'queen-elizabeth-cup',
                'name_en' => 'Queen Elizabeth II Cup',
                'name_jp' => 'エリザベス女王杯',
                'grade' => 'G1',
                'phase' => 'all',
                'surface' => 'turf',
                'distance_meters' => 2200,
                'distance_category' => 'medium',
                'venue' => 'Kyoto/Hanshin',
                'season' => 'autumn',
                'month_label' => 'November Year 2 & 3',
                'year_in_scenario' => null,
                'fan_requirement' => 1500,
                'fans_reward' => 1900,
                'sp_reward' => 55,
                'notes' => 'High-prestige autumn G1 for medium-distance builds. Strong rival field.',
            ],
            [
                'slug' => 'japan-cup',
                'name_en' => 'Japan Cup',
                'name_jp' => 'ジャパンカップ',
                'grade' => 'G1',
                'phase' => 'all',
                'surface' => 'turf',
                'distance_meters' => 2400,
                'distance_category' => 'long',
                'venue' => 'Tokyo',
                'season' => 'autumn',
                'month_label' => 'November Year 2 & 3',
                'year_in_scenario' => null,
                'fan_requirement' => 3000,
                'fans_reward' => 2500,
                'sp_reward' => 70,
                'stat_requirements' => ['speed' => 700, 'stamina' => 600],
                'notes' => 'International prestige race. High stat bar. Leads into year-end showdown.',
            ],
            [
                'slug' => 'arima-kinen',
                'name_en' => 'Arima Kinen (Grand Prix)',
                'name_jp' => '有馬記念',
                'grade' => 'G1',
                'phase' => 'all',
                'surface' => 'turf',
                'distance_meters' => 2500,
                'distance_category' => 'long',
                'venue' => 'Nakayama',
                'season' => 'winter',
                'month_label' => 'December Year 2 & 3',
                'year_in_scenario' => null,
                'fan_requirement' => 3500,
                'fans_reward' => 2800,
                'sp_reward' => 75,
                'stat_requirements' => ['speed' => 700, 'stamina' => 700, 'guts' => 500],
                'notes' => 'Year-end Grand Prix. Nakayama\'s tight corners favor guts and power builds.',
            ],

            // ──────────────────────────────────────────────────
            // SENIOR PHASE EXCLUSIVE  (Year 3+)
            // ──────────────────────────────────────────────────

            [
                'slug' => 'nikkei-sho',
                'name_en' => 'Nikkei Sho',
                'name_jp' => '日経賞',
                'grade' => 'G2',
                'phase' => 'senior',
                'surface' => 'turf',
                'distance_meters' => 2500,
                'distance_category' => 'long',
                'venue' => 'Nakayama',
                'season' => 'spring',
                'month_label' => 'March Year 3',
                'year_in_scenario' => 3,
                'fan_requirement' => 1000,
                'fans_reward' => 700,
                'sp_reward' => 22,
                'notes' => 'Senior G2 long distance. Good warm-up for Tenno Sho Spring long-distance path.',
            ],
            [
                'slug' => 'hanshin-daishogai',
                'name_en' => 'Hanshin Daishogai',
                'name_jp' => '阑神大賴外',
                'grade' => 'G2',
                'phase' => 'senior',
                'surface' => 'turf',
                'distance_meters' => 3000,
                'distance_category' => 'long',
                'venue' => 'Hanshin',
                'season' => 'spring',
                'month_label' => 'March Year 3',
                'year_in_scenario' => 3,
                'fan_requirement' => 1000,
                'fans_reward' => 750,
                'sp_reward' => 22,
                'notes' => 'Senior G2 at 3000m. Rare super-long prep race for ultra-stamina builds.',
            ],
            [
                'slug' => 'osaka-hai',
                'name_en' => 'Osaka Hai',
                'name_jp' => '大阪杯',
                'grade' => 'G1',
                'phase' => 'senior',
                'surface' => 'turf',
                'distance_meters' => 2000,
                'distance_category' => 'medium',
                'venue' => 'Hanshin',
                'season' => 'spring',
                'month_label' => 'April Year 3',
                'year_in_scenario' => 3,
                'fan_requirement' => 3000,
                'fans_reward' => 2200,
                'sp_reward' => 60,
                'notes' => 'Senior opening G1. Good warm-up target before Tenno Sho Spring.',
            ],
            [
                'slug' => 'meguro-kinen',
                'name_en' => 'Meguro Kinen',
                'name_jp' => '目黒記念',
                'grade' => 'G2',
                'phase' => 'senior',
                'surface' => 'turf',
                'distance_meters' => 2500,
                'distance_category' => 'long',
                'venue' => 'Tokyo',
                'season' => 'spring',
                'month_label' => 'May Year 3',
                'year_in_scenario' => 3,
                'fan_requirement' => 1200,
                'fans_reward' => 800,
                'sp_reward' => 25,
                'notes' => 'Senior G2 long distance at Tokyo. Good alternative path in late spring Year 3.',
            ],
            [
                'slug' => 'tenno-sho-spring',
                'name_en' => 'Tenno Sho (Spring)',
                'name_jp' => '天皇賞（春）',
                'grade' => 'G1',
                'phase' => 'senior',
                'surface' => 'turf',
                'distance_meters' => 3200,
                'distance_category' => 'super_long',
                'venue' => 'Kyoto/Hanshin',
                'season' => 'spring',
                'month_label' => 'May Year 3',
                'year_in_scenario' => 3,
                'fan_requirement' => 3000,
                'fans_reward' => 2400,
                'sp_reward' => 70,
                'stat_requirements' => ['stamina' => 900, 'guts' => 600],
                'notes' => 'Longest G1 in the URA catalog at 3200m. Maximum stamina required.',
            ],

            // ──────────────────────────────────────────────────
            // URA FINALE RACES
            // ──────────────────────────────────────────────────

            [
                'slug' => 'ura-preliminary',
                'name_en' => 'URA Finals — Preliminary',
                'name_jp' => 'URAファイナルズ 予選',
                'grade' => 'G1',
                'phase' => 'senior',
                'surface' => 'turf',
                'distance_meters' => 2000,
                'distance_category' => 'medium',
                'venue' => 'Various',
                'season' => 'winter',
                'month_label' => 'January Year 4',
                'year_in_scenario' => 4,
                'fan_requirement' => 0,
                'fans_reward' => 0,
                'sp_reward' => 0,
                'is_ura_finale' => true,
                'notes' => 'First URA Finale race. Must finish top 5 to advance.',
            ],
            [
                'slug' => 'ura-semifinal',
                'name_en' => 'URA Finals — Semi-Final',
                'name_jp' => 'URAファイナルズ 準決勝',
                'grade' => 'G1',
                'phase' => 'senior',
                'surface' => 'turf',
                'distance_meters' => 2400,
                'distance_category' => 'long',
                'venue' => 'Various',
                'season' => 'winter',
                'month_label' => 'February Year 4',
                'year_in_scenario' => 4,
                'fan_requirement' => 0,
                'fans_reward' => 0,
                'sp_reward' => 0,
                'is_ura_finale' => true,
                'notes' => 'Second URA Finale race. Must finish top 3 to advance.',
            ],
            [
                'slug' => 'ura-finals',
                'name_en' => 'URA Finals — Grand Prix',
                'name_jp' => 'URAファイナルズ 決勝',
                'grade' => 'G1',
                'phase' => 'senior',
                'surface' => 'turf',
                'distance_meters' => 3200,
                'distance_category' => 'super_long',
                'venue' => 'Various',
                'season' => 'winter',
                'month_label' => 'March Year 4',
                'year_in_scenario' => 4,
                'fan_requirement' => 0,
                'fans_reward' => 0,
                'sp_reward' => 0,
                'is_ura_finale' => true,
                'notes' => 'Final race of the URA scenario. Win for the ultimate ending. 3200m demands peak stamina/guts.',
            ],
        ];
    }
}
