<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UcpAptitudesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $characters = [
            'Special Week' => [
                'short_turf' => 'A',
                'mile_turf' => 'A',
                'intermediate_turf' => 'A',
                'long_turf' => 'B',
                'short_dirt' => 'G',
                'mile_dirt' => 'G',
                'intermediate_dirt' => 'G',
                'long_dirt' => 'G',
                'escape_turf' => 'G',
                'leading_turf' => 'A',
                'insert_turf' => 'A',
                'tracking_turf' => 'B',
                'escape_dirt' => 'G',
                'leading_dirt' => 'G',
                'insert_dirt' => 'G',
                'tracking_dirt' => 'G',
            ],
            'Silence Suzuka' => [
                'short_turf' => 'A',
                'mile_turf' => 'S',
                'intermediate_turf' => 'A',
                'long_turf' => 'B',
                'short_dirt' => 'G',
                'mile_dirt' => 'G',
                'intermediate_dirt' => 'G',
                'long_dirt' => 'G',
                'escape_turf' => 'S',
                'leading_turf' => 'A',
                'insert_turf' => 'B',
                'tracking_turf' => 'G',
                'escape_dirt' => 'G',
                'leading_dirt' => 'G',
                'insert_dirt' => 'G',
                'tracking_dirt' => 'G',
            ],
            'Tokai Teio' => [
                'short_turf' => 'B',
                'mile_turf' => 'A',
                'intermediate_turf' => 'S',
                'long_turf' => 'A',
                'short_dirt' => 'G',
                'mile_dirt' => 'G',
                'intermediate_dirt' => 'G',
                'long_dirt' => 'G',
                'escape_turf' => 'G',
                'leading_turf' => 'A',
                'insert_turf' => 'S',
                'tracking_turf' => 'A',
                'escape_dirt' => 'G',
                'leading_dirt' => 'G',
                'insert_dirt' => 'G',
                'tracking_dirt' => 'G',
            ],
            'Maruzensky' => [
                'short_turf' => 'G',
                'mile_turf' => 'B',
                'intermediate_turf' => 'A',
                'long_turf' => 'S',
                'short_dirt' => 'G',
                'mile_dirt' => 'G',
                'intermediate_dirt' => 'G',
                'long_dirt' => 'G',
                'escape_turf' => 'G',
                'leading_turf' => 'B',
                'insert_turf' => 'A',
                'tracking_turf' => 'S',
                'escape_dirt' => 'G',
                'leading_dirt' => 'G',
                'insert_dirt' => 'G',
                'tracking_dirt' => 'G',
            ],
            'Fuji Kiseki' => [
                'short_turf' => 'S',
                'mile_turf' => 'A',
                'intermediate_turf' => 'B',
                'long_turf' => 'G',
                'short_dirt' => 'G',
                'mile_dirt' => 'G',
                'intermediate_dirt' => 'G',
                'long_dirt' => 'G',
                'escape_turf' => 'A',
                'leading_turf' => 'S',
                'insert_turf' => 'B',
                'tracking_turf' => 'G',
                'escape_dirt' => 'G',
                'leading_dirt' => 'G',
                'insert_dirt' => 'G',
                'tracking_dirt' => 'G',
            ],
            'Oguri Cap' => [
                'short_turf' => 'G',
                'mile_turf' => 'A',
                'intermediate_turf' => 'S',
                'long_turf' => 'S',
                'short_dirt' => 'G',
                'mile_dirt' => 'G',
                'intermediate_dirt' => 'G',
                'long_dirt' => 'G',
                'escape_turf' => 'G',
                'leading_turf' => 'G',
                'insert_turf' => 'A',
                'tracking_turf' => 'S',
                'escape_dirt' => 'G',
                'leading_dirt' => 'G',
                'insert_dirt' => 'G',
                'tracking_dirt' => 'G',
            ],
            'Gold Ship' => [
                'short_turf' => 'G',
                'mile_turf' => 'B',
                'intermediate_turf' => 'A',
                'long_turf' => 'S',
                'short_dirt' => 'G',
                'mile_dirt' => 'G',
                'intermediate_dirt' => 'G',
                'long_dirt' => 'G',
                'escape_turf' => 'G',
                'leading_turf' => 'G',
                'insert_turf' => 'B',
                'tracking_turf' => 'A',
                'escape_dirt' => 'G',
                'leading_dirt' => 'G',
                'insert_dirt' => 'G',
                'tracking_dirt' => 'G',
            ],
            'Vodka' => [
                'short_turf' => 'B',
                'mile_turf' => 'A',
                'intermediate_turf' => 'S',
                'long_turf' => 'A',
                'short_dirt' => 'G',
                'mile_dirt' => 'G',
                'intermediate_dirt' => 'G',
                'long_dirt' => 'G',
                'escape_turf' => 'G',
                'leading_turf' => 'B',
                'insert_turf' => 'A',
                'tracking_turf' => 'S',
                'escape_dirt' => 'G',
                'leading_dirt' => 'G',
                'insert_dirt' => 'G',
                'tracking_dirt' => 'G',
            ],
            'Daiwa Scarlet' => [
                'short_turf' => 'A',
                'mile_turf' => 'S',
                'intermediate_turf' => 'A',
                'long_turf' => 'B',
                'short_dirt' => 'G',
                'mile_dirt' => 'G',
                'intermediate_dirt' => 'G',
                'long_dirt' => 'G',
                'escape_turf' => 'B',
                'leading_turf' => 'S',
                'insert_turf' => 'A',
                'tracking_turf' => 'G',
                'escape_dirt' => 'G',
                'leading_dirt' => 'G',
                'insert_dirt' => 'G',
                'tracking_dirt' => 'G',
            ],
            'Taiki Shuttle' => [
                'short_turf' => 'S',
                'mile_turf' => 'A',
                'intermediate_turf' => 'G',
                'long_turf' => 'G',
                'short_dirt' => 'A',
                'mile_dirt' => 'B',
                'intermediate_dirt' => 'G',
                'long_dirt' => 'G',
                'escape_turf' => 'S',
                'leading_turf' => 'A',
                'insert_turf' => 'G',
                'tracking_turf' => 'G',
                'escape_dirt' => 'A',
                'leading_dirt' => 'B',
                'insert_dirt' => 'G',
                'tracking_dirt' => 'G',
            ],
        ];

        foreach ($characters as $characterName => $aptitudes) {
            DB::table('ucp_aptitudes')->insert([
                'character_name' => $characterName,
                'character_internal_id' => strtolower(str_replace(' ', '_', $characterName)),
                'short_turf' => $aptitudes['short_turf'],
                'mile_turf' => $aptitudes['mile_turf'],
                'intermediate_turf' => $aptitudes['intermediate_turf'],
                'long_turf' => $aptitudes['long_turf'],
                'short_dirt' => $aptitudes['short_dirt'],
                'mile_dirt' => $aptitudes['mile_dirt'],
                'intermediate_dirt' => $aptitudes['intermediate_dirt'],
                'long_dirt' => $aptitudes['long_dirt'],
                'escape_turf' => $aptitudes['escape_turf'],
                'leading_turf' => $aptitudes['leading_turf'],
                'insert_turf' => $aptitudes['insert_turf'],
                'tracking_turf' => $aptitudes['tracking_turf'],
                'escape_dirt' => $aptitudes['escape_dirt'],
                'leading_dirt' => $aptitudes['leading_dirt'],
                'insert_dirt' => $aptitudes['insert_dirt'],
                'tracking_dirt' => $aptitudes['tracking_dirt'],
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}
