<?php

declare(strict_types=1);

namespace App\Enums;

/**
 * Alert Type Enum
 *
 * Defines the types of critical alerts that can be generated by the
 * AI-Powered Training Advisory System.
 *
 * @see \App\Services\CriticalSituationDetector
 * @see \App\Models\CriticalAlert
 */
enum AlertType: string
{
    /**
     * Stamina crisis alert
     *
     * Triggered when character's stamina is insufficient for upcoming race
     * distance requirements. Requires immediate stamina training focus.
     */
    case STAMINA_CRISIS = 'stamina_crisis';

    /**
     * SP shortage alert
     *
     * Triggered when SP budget is insufficient for planned skill purchases.
     * Typical budget is 300-500 SP per career.
     */
    case SP_SHORTAGE = 'sp_shortage';

    /**
     * Energy critical alert
     *
     * Triggered when energy drops below 40, causing high failure rates
     * and reduced training effectiveness.
     */
    case ENERGY_CRITICAL = 'energy_critical';

    /**
     * Bond behind schedule alert
     *
     * Triggered when support card bonds are below 80 by Turn 25,
     * risking loss of Friendship Training opportunities.
     */
    case BOND_BEHIND_SCHEDULE = 'bond_behind_schedule';

    /**
     * Facility imbalance alert
     *
     * Triggered when facility levels are significantly unbalanced
     * (e.g., Level 5 Speed but Level 1 Stamina).
     */
    case FACILITY_IMBALANCE = 'facility_imbalance';

    /**
     * Race unready alert
     *
     * Triggered when character stats are insufficient for upcoming race
     * requirements (distance, competition level, terrain).
     */
    case RACE_UNREADY = 'race_unready';

    /**
     * Team race unprepared alert
     *
     * Triggered when Unity Cup scenario team race requirements are not met.
     */
    case TEAM_RACE_UNPREPARED = 'team_race_unprepared';

    /**
     * Get a human-readable label for the alert type
     */
    public function label(): string
    {
        return match ($this) {
            self::STAMINA_CRISIS => 'Stamina Crisis',
            self::SP_SHORTAGE => 'SP Shortage',
            self::ENERGY_CRITICAL => 'Energy Critical',
            self::BOND_BEHIND_SCHEDULE => 'Bond Behind Schedule',
            self::FACILITY_IMBALANCE => 'Facility Imbalance',
            self::RACE_UNREADY => 'Race Unready',
            self::TEAM_RACE_UNPREPARED => 'Team Race Unprepared',
        };
    }

    /**
     * Get a description of the alert type
     */
    public function description(): string
    {
        return match ($this) {
            self::STAMINA_CRISIS => 'Stamina insufficient for upcoming race distance',
            self::SP_SHORTAGE => 'SP budget insufficient for planned skill purchases',
            self::ENERGY_CRITICAL => 'Energy too low, high failure rate risk',
            self::BOND_BEHIND_SCHEDULE => 'Support card bonds below target for Friendship Training',
            self::FACILITY_IMBALANCE => 'Training facility levels significantly unbalanced',
            self::RACE_UNREADY => 'Character stats insufficient for upcoming race',
            self::TEAM_RACE_UNPREPARED => 'Team race requirements not met',
        };
    }

    /**
     * Get an icon class for the alert type (for UI display)
     */
    public function icon(): string
    {
        return match ($this) {
            self::STAMINA_CRISIS => 'stamina-warning',
            self::SP_SHORTAGE => 'sp-warning',
            self::ENERGY_CRITICAL => 'energy-warning',
            self::BOND_BEHIND_SCHEDULE => 'bond-warning',
            self::FACILITY_IMBALANCE => 'facility-warning',
            self::RACE_UNREADY => 'race-warning',
            self::TEAM_RACE_UNPREPARED => 'team-warning',
        };
    }

    /**
     * Get the default priority for this alert type
     */
    public function defaultPriority(): Priority
    {
        return match ($this) {
            self::STAMINA_CRISIS => Priority::CRITICAL,
            self::SP_SHORTAGE => Priority::HIGH,
            self::ENERGY_CRITICAL => Priority::CRITICAL,
            self::BOND_BEHIND_SCHEDULE => Priority::HIGH,
            self::FACILITY_IMBALANCE => Priority::MEDIUM,
            self::RACE_UNREADY => Priority::CRITICAL,
            self::TEAM_RACE_UNPREPARED => Priority::CRITICAL,
        };
    }

    /**
     * Check if this alert type is stat-related
     */
    public function isStatRelated(): bool
    {
        return in_array($this, [
            self::STAMINA_CRISIS,
            self::FACILITY_IMBALANCE,
        ], true);
    }

    /**
     * Check if this alert type is race-related
     */
    public function isRaceRelated(): bool
    {
        return in_array($this, [
            self::STAMINA_CRISIS,
            self::RACE_UNREADY,
            self::TEAM_RACE_UNPREPARED,
        ], true);
    }

    /**
     * Check if this alert type is training-related
     */
    public function isTrainingRelated(): bool
    {
        return in_array($this, [
            self::ENERGY_CRITICAL,
            self::BOND_BEHIND_SCHEDULE,
            self::FACILITY_IMBALANCE,
        ], true);
    }

    /**
     * Get all alert types
     *
     * @return array<self>
     */
    public static function all(): array
    {
        return self::cases();
    }

    /**
     * Get all alert type values
     *
     * @return array<string>
     */
    public static function values(): array
    {
        return array_map(fn (self $type) => $type->value, self::cases());
    }
}
