<?php

declare(strict_types=1);

namespace App\Enums;

/**
 * Recommendation Type Enum
 *
 * Defines the types of recommendations that can be generated by the
 * AI-Powered Training Advisory System.
 *
 * @see \App\Services\TrainingAdvisoryService
 */
enum RecommendationType: string
{
    /**
     * Training facility recommendation
     *
     * Recommends which training facility to use based on support card presence,
     * facility levels, character stats, and phase goals.
     */
    case TRAINING_FACILITY = 'training_facility';

    /**
     * Skill purchase recommendation
     *
     * Recommends which skills to purchase based on SP budget, hint levels,
     * skill tier (gold/rare/normal), and character build strategy.
     */
    case SKILL_PURCHASE = 'skill_purchase';

    /**
     * Race strategy recommendation
     *
     * Recommends race strategy including running style, readiness assessment,
     * and win probability calculations.
     */
    case RACE_STRATEGY = 'race_strategy';

    /**
     * Rest and recovery recommendation
     *
     * Recommends rest or recovery actions when energy is low or character
     * is at risk of training failure.
     */
    case REST_RECOVERY = 'rest_recovery';

    /**
     * Bond building recommendation
     *
     * Recommends actions to build bonds with support cards to unlock
     * Friendship Training and maximize training effectiveness.
     */
    case BOND_BUILDING = 'bond_building';

    /**
     * Get a human-readable label for the recommendation type
     */
    public function label(): string
    {
        return match ($this) {
            self::TRAINING_FACILITY => 'Training Facility',
            self::SKILL_PURCHASE => 'Skill Purchase',
            self::RACE_STRATEGY => 'Race Strategy',
            self::REST_RECOVERY => 'Rest & Recovery',
            self::BOND_BUILDING => 'Bond Building',
        };
    }

    /**
     * Get a description of the recommendation type
     */
    public function description(): string
    {
        return match ($this) {
            self::TRAINING_FACILITY => 'Recommendations for which training facility to use',
            self::SKILL_PURCHASE => 'Recommendations for which skills to purchase',
            self::RACE_STRATEGY => 'Recommendations for race preparation and strategy',
            self::REST_RECOVERY => 'Recommendations for rest and energy recovery',
            self::BOND_BUILDING => 'Recommendations for building support card bonds',
        };
    }

    /**
     * Get an icon class for the recommendation type (for UI display)
     */
    public function icon(): string
    {
        return match ($this) {
            self::TRAINING_FACILITY => 'facility',
            self::SKILL_PURCHASE => 'skill',
            self::RACE_STRATEGY => 'race',
            self::REST_RECOVERY => 'rest',
            self::BOND_BUILDING => 'bond',
        };
    }

    /**
     * Check if this recommendation type is training-related
     */
    public function isTrainingRelated(): bool
    {
        return in_array($this, [
            self::TRAINING_FACILITY,
            self::REST_RECOVERY,
            self::BOND_BUILDING,
        ], true);
    }

    /**
     * Check if this recommendation type is strategic (requires planning)
     */
    public function isStrategic(): bool
    {
        return in_array($this, [
            self::SKILL_PURCHASE,
            self::RACE_STRATEGY,
        ], true);
    }

    /**
     * Get all recommendation types
     *
     * @return array<self>
     */
    public static function all(): array
    {
        return self::cases();
    }

    /**
     * Get all recommendation type values
     *
     * @return array<string>
     */
    public static function values(): array
    {
        return array_map(fn (self $type) => $type->value, self::cases());
    }

    /**
     * Try to create an instance from a string value
     *
     * Note: This method is already provided by PHP's BackedEnum interface,
     * but we document it here for clarity.
     */
}
